name: test
on:
  push:
    branches:
      - develop
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{matrix.java}}
    - name: Test
      run: sbt -Dfile.encoding=UTF8 compilerInterface/headerCheck jvmfmtCheck dummyBridge/test doc
